package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_vi extends ListResourceBundle {
    private static final Object[][] contents = {
        { "AbstractButton.clickText", "click" },
        { "AbstractDocument.additionText", "thêm" },
        { "AbstractDocument.deletionText", "xóa" },
        { "AbstractDocument.redoText", "Làm lại" },
        { "AbstractDocument.styleChangeText", "đổi kiểu" },
        { "AbstractDocument.undoText", "Hồi lại" },
        { "AbstractUndoableEdit.redoText", "Làm lại" },
        { "AbstractUndoableEdit.undoText", "Hồi lại" },
        { "ColorChooser.cancelText", "Bãi" },
        { "ColorChooser.hsbBlueText", "B" },
        { "ColorChooser.hsbBrightnessText", "B" },
        { "ColorChooser.hsbDisplayedMnemonicIndex", "0" },
        { "ColorChooser.hsbGreenText", "G" },
        { "ColorChooser.hsbHueText", "H" },
        { "ColorChooser.hsbMnemonic", "72" },
        { "ColorChooser.hsbNameText", "HSB" },
        { "ColorChooser.hsbRedText", "R" },
        { "ColorChooser.hsbSaturationText", "S" },
        { "ColorChooser.okText", "Được" },
        { "ColorChooser.previewText", "Xem trước" },
        { "ColorChooser.resetMnemonic", "82" },
        { "ColorChooser.resetText", "Đặt Lại" },
        { "ColorChooser.rgbBlueText", "Xanh" },
        { "ColorChooser.rgbDisplayedMnemonicIndex", "1" },
        { "ColorChooser.rgbGreenText", "Xanh lá cây" },
        { "ColorChooser.rgbMnemonic", "71" },
        { "ColorChooser.rgbNameText", "RGB" },
        { "ColorChooser.rgbRedText", "Đỏ" },
        { "ColorChooser.sampleText", "Văn bản mẫu  Văn bản mẫu" },
        { "ColorChooser.swatchesDisplayedMnemonicIndex", "0" },
        { "ColorChooser.swatchesMnemonic", "83" },
        { "ColorChooser.swatchesNameText", "Mẫu màu" },
        { "ColorChooser.swatchesRecentText", "Mới đây:" },
        { "ComboBox.togglePopupText", "togglePopup" },
        { "FileChooser.acceptAllFileFilterText", "Tất cả" },
        { "FileChooser.cancelButtonText", "Bãi" },
        { "FileChooser.cancelButtonToolTipText", "Hủy hộp thoại file chooser" },
        { "FileChooser.directoryDescriptionText", "Thư mục" },
        { "FileChooser.directoryOpenButtonText", "Mở" },
        { "FileChooser.directoryOpenButtonToolTipText", "Mở thư mục được chọn" },
        { "FileChooser.fileDescriptionText", "Tập tin tổng quát" },
        { "FileChooser.helpButtonText", "Trợ giúp" },
        { "FileChooser.helpButtonToolTipText", "FileChooser trợ giúp" },
        { "FileChooser.newFolderErrorSeparator", ": " },
        { "FileChooser.newFolderErrorText", "Lỗi trong khi tạo hồ sơ mới" },
        { "FileChooser.openButtonText", "Mở" },
        { "FileChooser.openButtonToolTipText", "Mở tập tin được chọn" },
        { "FileChooser.openDialogTitleText", "Mở" },
        { "FileChooser.other.newFolder", "HồSơMới" },
        { "FileChooser.other.newFolder.subsequent", "HồSơMới.{0}" },
        { "FileChooser.saveButtonText", "Lưu" },
        { "FileChooser.saveButtonToolTipText", "Lưu tập tin được chọn" },
        { "FileChooser.saveDialogTitleText", "Lưu" },
        { "FileChooser.updateButtonText", "Cập nhật" },
        { "FileChooser.updateButtonToolTipText", "Cập nhật danh sách thư mục" },
        { "FileChooser.win32.newFolder", "Hồ sơ mới" },
        { "FileChooser.win32.newFolder.subsequent", "Hồ sơ mới ({0})" },
        { "FormView.browseFileButtonText", "Browse..." },
        { "FormView.resetButtonText", "Reset" },
        { "FormView.submitButtonText", "Submit Query" },
        { "InternalFrame.closeButtonToolTip", "Đóng" },
        { "InternalFrame.iconButtonToolTip", "Tối thiểu" },
        { "InternalFrame.maxButtonToolTip", "Tối đa" },
        { "InternalFrame.restoreButtonToolTip", "Tái hồi" },
        { "InternalFrameTitlePane.closeButtonText", "Đóng" },
        { "InternalFrameTitlePane.maximizeButtonText", "Tối đa" },
        { "InternalFrameTitlePane.minimizeButtonText", "Tối thiểu" },
        { "InternalFrameTitlePane.moveButtonText", "Dời" },
        { "InternalFrameTitlePane.restoreButtonText", "Tái hồi" },
        { "InternalFrameTitlePane.sizeButtonText", "Kích thước" },
        { "IsindexView.prompt", "This is a searchable index.  Enter search keywords:" },
        { "OptionPane.cancelButtonMnemonic", "0" },
        { "OptionPane.cancelButtonText", "Bãi" },
        { "OptionPane.inputDialogTitle", "Nhập" },
        { "OptionPane.messageDialogTitle", "Thông tin" },
        { "OptionPane.noButtonMnemonic", "78" },
        { "OptionPane.noButtonText", "Không" },
        { "OptionPane.okButtonMnemonic", "0" },
        { "OptionPane.okButtonText", "Được" },
        { "OptionPane.titleText", "Chọn một" },
        { "OptionPane.yesButtonMnemonic", "89" },
        { "OptionPane.yesButtonText", "Có" },
        { "ProgressMonitor.progressText", "Tiến triển..." },
        { "SplitPane.leftButtonText", "nút trái" },
        { "SplitPane.rightButtonText", "nút phải" },
    };

    protected final Object[][] getContents() {
         return contents;
    }
}
